2017-10-27 12:45:57,453 ERROR GetRowByDbWhere,[具体信息]:Traceback (most recent call last):
  File "E:/projecting/yl_sqlmap/2.SRC\iLibP2\dalbase.py", line 91, in GetRowByDbWhere
    recs=self.db.select(self.table_name,**where_args)
  File "C:\Python27\lib\site-packages\web\db.py", line 705, in select
    return self.query(qout, processed=True)
  File "C:\Python27\lib\site-packages\web\db.py", line 664, in query
    db_cursor = self._db_cursor()
  File "C:\Python27\lib\site-packages\web\db.py", line 575, in _db_cursor
    return self.ctx.db.cursor()
  File "C:\Python27\lib\site-packages\web\db.py", line 516, in _getctx
    self._load_context(self._ctx)
  File "C:\Python27\lib\site-packages\web\db.py", line 525, in _load_context
    ctx.db = self._connect_with_pooling(self.keywords)
  File "C:\Python27\lib\site-packages\web\db.py", line 572, in _connect_with_pooling
    return self._pooleddb.connection()
  File "C:\Python27\lib\site-packages\DBUtils\PooledDB.py", line 334, in connection
    con = self.steady_connection()
  File "C:\Python27\lib\site-packages\DBUtils\PooledDB.py", line 282, in steady_connection
    *self._args, **self._kwargs)
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 142, in connect
    failures, ping, closeable, *args, **kwargs)
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 194, in __init__
    self._store(self._create())
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 198, in _create
    con = self._creator(*self._args, **self._kwargs)
  File "C:\Python27\lib\site-packages\MySQLdb\__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: an integer is required
,
[参数]:
{'where': 'username=$un', 'vars': {'un': u'admin'}}
[数据]:
an integer is required
2017-10-27 12:46:00,407 ERROR GetRowByDbWhere,[具体信息]:Traceback (most recent call last):
  File "E:/projecting/yl_sqlmap/2.SRC\iLibP2\dalbase.py", line 91, in GetRowByDbWhere
    recs=self.db.select(self.table_name,**where_args)
  File "C:\Python27\lib\site-packages\web\db.py", line 705, in select
    return self.query(qout, processed=True)
  File "C:\Python27\lib\site-packages\web\db.py", line 664, in query
    db_cursor = self._db_cursor()
  File "C:\Python27\lib\site-packages\web\db.py", line 575, in _db_cursor
    return self.ctx.db.cursor()
  File "C:\Python27\lib\site-packages\web\db.py", line 516, in _getctx
    self._load_context(self._ctx)
  File "C:\Python27\lib\site-packages\web\db.py", line 525, in _load_context
    ctx.db = self._connect_with_pooling(self.keywords)
  File "C:\Python27\lib\site-packages\web\db.py", line 572, in _connect_with_pooling
    return self._pooleddb.connection()
  File "C:\Python27\lib\site-packages\DBUtils\PooledDB.py", line 334, in connection
    con = self.steady_connection()
  File "C:\Python27\lib\site-packages\DBUtils\PooledDB.py", line 282, in steady_connection
    *self._args, **self._kwargs)
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 142, in connect
    failures, ping, closeable, *args, **kwargs)
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 194, in __init__
    self._store(self._create())
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 198, in _create
    con = self._creator(*self._args, **self._kwargs)
  File "C:\Python27\lib\site-packages\MySQLdb\__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: an integer is required
,
[参数]:
{'where': 'username=$un', 'vars': {'un': u'admin'}}
[数据]:
an integer is required
2017-10-27 12:46:06,144 ERROR GetRowByDbWhere,[具体信息]:Traceback (most recent call last):
  File "E:/projecting/yl_sqlmap/2.SRC\iLibP2\dalbase.py", line 91, in GetRowByDbWhere
    recs=self.db.select(self.table_name,**where_args)
  File "C:\Python27\lib\site-packages\web\db.py", line 705, in select
    return self.query(qout, processed=True)
  File "C:\Python27\lib\site-packages\web\db.py", line 664, in query
    db_cursor = self._db_cursor()
  File "C:\Python27\lib\site-packages\web\db.py", line 575, in _db_cursor
    return self.ctx.db.cursor()
  File "C:\Python27\lib\site-packages\web\db.py", line 516, in _getctx
    self._load_context(self._ctx)
  File "C:\Python27\lib\site-packages\web\db.py", line 525, in _load_context
    ctx.db = self._connect_with_pooling(self.keywords)
  File "C:\Python27\lib\site-packages\web\db.py", line 572, in _connect_with_pooling
    return self._pooleddb.connection()
  File "C:\Python27\lib\site-packages\DBUtils\PooledDB.py", line 334, in connection
    con = self.steady_connection()
  File "C:\Python27\lib\site-packages\DBUtils\PooledDB.py", line 282, in steady_connection
    *self._args, **self._kwargs)
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 142, in connect
    failures, ping, closeable, *args, **kwargs)
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 194, in __init__
    self._store(self._create())
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 198, in _create
    con = self._creator(*self._args, **self._kwargs)
  File "C:\Python27\lib\site-packages\MySQLdb\__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: an integer is required
,
[参数]:
{'where': 'username=$un', 'vars': {'un': u'admin'}}
[数据]:
an integer is required
2017-10-27 12:47:37,924 ERROR GetRowByDbWhere,[具体信息]:Traceback (most recent call last):
  File "E:/projecting/yl_sqlmap/2.SRC\iLibP2\dalbase.py", line 91, in GetRowByDbWhere
    recs=self.db.select(self.table_name,**where_args)
  File "C:\Python27\lib\site-packages\web\db.py", line 705, in select
    return self.query(qout, processed=True)
  File "C:\Python27\lib\site-packages\web\db.py", line 664, in query
    db_cursor = self._db_cursor()
  File "C:\Python27\lib\site-packages\web\db.py", line 575, in _db_cursor
    return self.ctx.db.cursor()
  File "C:\Python27\lib\site-packages\web\db.py", line 516, in _getctx
    self._load_context(self._ctx)
  File "C:\Python27\lib\site-packages\web\db.py", line 525, in _load_context
    ctx.db = self._connect_with_pooling(self.keywords)
  File "C:\Python27\lib\site-packages\web\db.py", line 572, in _connect_with_pooling
    return self._pooleddb.connection()
  File "C:\Python27\lib\site-packages\DBUtils\PooledDB.py", line 334, in connection
    con = self.steady_connection()
  File "C:\Python27\lib\site-packages\DBUtils\PooledDB.py", line 282, in steady_connection
    *self._args, **self._kwargs)
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 142, in connect
    failures, ping, closeable, *args, **kwargs)
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 194, in __init__
    self._store(self._create())
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 198, in _create
    con = self._creator(*self._args, **self._kwargs)
  File "C:\Python27\lib\site-packages\MySQLdb\__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: an integer is required
,
[参数]:
{'where': 'username=$un', 'vars': {'un': u'admin'}}
[数据]:
an integer is required
2017-10-27 12:48:00,160 ERROR GetRowByDbWhere,[具体信息]:Traceback (most recent call last):
  File "E:/projecting/yl_sqlmap/2.SRC\iLibP2\dalbase.py", line 91, in GetRowByDbWhere
    recs=self.db.select(self.table_name,**where_args)
  File "C:\Python27\lib\site-packages\web\db.py", line 705, in select
    return self.query(qout, processed=True)
  File "C:\Python27\lib\site-packages\web\db.py", line 664, in query
    db_cursor = self._db_cursor()
  File "C:\Python27\lib\site-packages\web\db.py", line 575, in _db_cursor
    return self.ctx.db.cursor()
  File "C:\Python27\lib\site-packages\web\db.py", line 516, in _getctx
    self._load_context(self._ctx)
  File "C:\Python27\lib\site-packages\web\db.py", line 525, in _load_context
    ctx.db = self._connect_with_pooling(self.keywords)
  File "C:\Python27\lib\site-packages\web\db.py", line 572, in _connect_with_pooling
    return self._pooleddb.connection()
  File "C:\Python27\lib\site-packages\DBUtils\PooledDB.py", line 334, in connection
    con = self.steady_connection()
  File "C:\Python27\lib\site-packages\DBUtils\PooledDB.py", line 282, in steady_connection
    *self._args, **self._kwargs)
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 142, in connect
    failures, ping, closeable, *args, **kwargs)
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 194, in __init__
    self._store(self._create())
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 198, in _create
    con = self._creator(*self._args, **self._kwargs)
  File "C:\Python27\lib\site-packages\MySQLdb\__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: an integer is required
,
[参数]:
{'where': 'username=$un', 'vars': {'un': u'admin'}}
[数据]:
an integer is required
2017-10-27 12:51:00,878 ERROR GetRowByDbWhere,[具体信息]:Traceback (most recent call last):
  File "E:/projecting/yl_sqlmap/2.SRC\iLibP2\dalbase.py", line 91, in GetRowByDbWhere
    recs=self.db.select(self.table_name,**where_args)
  File "C:\Python27\lib\site-packages\web\db.py", line 705, in select
    return self.query(qout, processed=True)
  File "C:\Python27\lib\site-packages\web\db.py", line 664, in query
    db_cursor = self._db_cursor()
  File "C:\Python27\lib\site-packages\web\db.py", line 575, in _db_cursor
    return self.ctx.db.cursor()
  File "C:\Python27\lib\site-packages\web\db.py", line 516, in _getctx
    self._load_context(self._ctx)
  File "C:\Python27\lib\site-packages\web\db.py", line 525, in _load_context
    ctx.db = self._connect_with_pooling(self.keywords)
  File "C:\Python27\lib\site-packages\web\db.py", line 572, in _connect_with_pooling
    return self._pooleddb.connection()
  File "C:\Python27\lib\site-packages\DBUtils\PooledDB.py", line 334, in connection
    con = self.steady_connection()
  File "C:\Python27\lib\site-packages\DBUtils\PooledDB.py", line 282, in steady_connection
    *self._args, **self._kwargs)
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 142, in connect
    failures, ping, closeable, *args, **kwargs)
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 194, in __init__
    self._store(self._create())
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 198, in _create
    con = self._creator(*self._args, **self._kwargs)
  File "C:\Python27\lib\site-packages\MySQLdb\__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: an integer is required
,
[参数]:
{'where': 'username=$un', 'vars': {'un': u'admin'}}
[数据]:
an integer is required
2017-10-27 12:51:15,013 ERROR iSQL初始化出错,[具体信息]:Traceback (most recent call last):
  File "E:/projecting/yl_sqlmap/2.SRC\iLibP2\isql.py", line 38, in __init__
    self.__root     = ET.parse(TP_PATH+"/"+sqlmapconfig)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1177, in parse
    tree.parse(source, parser)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 653, in parse
    parser.feed(data)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1624, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1488, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 8, column 46
,[数据]:
not well-formed (invalid token): line 8, column 46
2017-10-27 14:14:49,140 ERROR iLib执行GetCount函数出错,[具体信息]:Traceback (most recent call last):
  File "E:/projecting/yl_sqlmap/2.SRC\iLibP2\dalbase.py", line 201, in GetCount
    r=self.db.select(self.table_name,**dbwhere)
  File "C:\Python27\lib\site-packages\web\db.py", line 702, in select
    clauses = [self.gen_clause(sql, val, vars) for sql, val in sql_clauses if val is not None]
  File "C:\Python27\lib\site-packages\web\db.py", line 749, in gen_clause
    nout = reparam(val, vars)
  File "C:\Python27\lib\site-packages\web\db.py", line 309, in reparam
    v = eval(chunk, dictionary)
  File "<string>", line 1, in <module>
NameError: name 'funno' is not defined

2017-10-27 14:16:00,512 ERROR iLib执行GetCount函数出错,[具体信息]:Traceback (most recent call last):
  File "E:/projecting/yl_sqlmap/2.SRC\iLibP2\dalbase.py", line 201, in GetCount
    r=self.db.select(self.table_name,**dbwhere)
  File "C:\Python27\lib\site-packages\web\db.py", line 705, in select
    return self.query(qout, processed=True)
  File "C:\Python27\lib\site-packages\web\db.py", line 665, in query
    self._db_execute(db_cursor, sql_query)
  File "C:\Python27\lib\site-packages\web\db.py", line 596, in _db_execute
    out = cur.execute(query, params)
  File "C:\Python27\lib\site-packages\DBUtils\SteadyDB.py", line 580, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "C:\Python27\lib\site-packages\MySQLdb\cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'and funno='0011' ORDER BY funno asc' at line 1")

2017-10-27 14:45:56,056 ERROR iLib执行Save函数出错,[具体信息]:Traceback (most recent call last):
  File "E:/projecting/yl_sqlmap/2.SRC\iLibP2\dalbase.py", line 159, in Save
    raise Exception,u"传入数据需要包括数据表的主键属性值"
Exception: 传入数据需要包括数据表的主键属性值
,
[参数]:
<Storage {'funname': u'', 'id': 0, 'funno': u'0012'}>
[数据]:
传入数据需要包括数据表的主键属性值
